// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6qSLF7zNEF6Sbr9V5tYj9YSOvqAartCQ',
    appId: '1:972665082655:web:16651b208ac04afda2562a',
    messagingSenderId: '972665082655',
    projectId: 'realitycart-a1e3f',
    authDomain: 'realitycart-a1e3f.firebaseapp.com',
    storageBucket: 'realitycart-a1e3f.firebasestorage.app',
    measurementId: 'G-22QJFWQ62N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs893C8ibiFzUE8GciEoJA6OlCbkte3Ks',
    appId: '1:972665082655:android:871be5307b813a33a2562a',
    messagingSenderId: '972665082655',
    projectId: 'realitycart-a1e3f',
    storageBucket: 'realitycart-a1e3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1C4mC2o2rcgvDKZhUrV3KjQIuXdBfw8E',
    appId: '1:972665082655:ios:3bfd1e1de99013eca2562a',
    messagingSenderId: '972665082655',
    projectId: 'realitycart-a1e3f',
    storageBucket: 'realitycart-a1e3f.firebasestorage.app',
    iosBundleId: 'com.example.realityCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1C4mC2o2rcgvDKZhUrV3KjQIuXdBfw8E',
    appId: '1:972665082655:ios:3bfd1e1de99013eca2562a',
    messagingSenderId: '972665082655',
    projectId: 'realitycart-a1e3f',
    storageBucket: 'realitycart-a1e3f.firebasestorage.app',
    iosBundleId: 'com.example.realityCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6qSLF7zNEF6Sbr9V5tYj9YSOvqAartCQ',
    appId: '1:972665082655:web:72a1f23cec3d1526a2562a',
    messagingSenderId: '972665082655',
    projectId: 'realitycart-a1e3f',
    authDomain: 'realitycart-a1e3f.firebaseapp.com',
    storageBucket: 'realitycart-a1e3f.firebasestorage.app',
    measurementId: 'G-8M8TRLCGDS',
  );
}
